# Taken from https://www.edureka.co/blog/docker-compose-containerizing-mean-stack-application/
# Modified by Logan Ramos
version: '3.0' # specify docker-compose version
 
# Define the services/ containers to be run
services:
  angular: # name of the first service
    build: angular-app # specify the directory of the Dockerfile
    ports:
    - "4200:4200"
    - "49153:49153" # specify port mapping
    volumes:
    - ./angular-app:/usr/src/app
    - /usr/src/app/node_modules/
 
  express: # name of the second service
    build: express-server # specify the directory of the Dockerfile
    ports:
    - "3000:3000" #specify ports mapping
    links:
    - database # link this service to the database service
    volumes:
    - ./express-server:/usr/src/app
    - /usr/src/app/node_modules/
    depends_on:
    - database
 
  adminer:
    image: adminer
    ports:
    - "8080:8080"
    links:
    - database
  
  database: # name of the third service
    image: mariadb # specify image to build container from
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=training
    volumes:
    - ./database-files:/docker-entrypoint-initdb.d
    ports:
    - "3306:3306" # specify port forwarding